### ISSUE TITLE
USER_BASE cannot be imported

### ISSUE THREAD

**Issue by ronaldoussoren** [ronaldoussoren/py2app#111]
**[Original report](https://bitbucket.org/ronaldoussoren/py2app/issue/111) by Gregor Peach (Bitbucket: [Others](https://bitbucket.org/Others), GitHub: [Others](https://github.com/Others)).**

----------------------------------------

I folowed the instrucitions found here:
http://pythonhosted.org/py2app/tutorial.html
However when I run the .app found in the dist folder
It fails and when I look in the terminal It says that it cannot import user base like so:
4/18/13 7:41:15.359 PM [0x0-0x133133].org.pythonmac.unspecified.FAIL: argvemulator warning: fetching events failed
4/18/13 7:41:15.359 PM [0x0-0x133133].org.pythonmac.unspecified.FAIL: Traceback (most recent call last):
4/18/13 7:41:15.359 PM [0x0-0x133133].org.pythonmac.unspecified.FAIL:   File "/Users/peachg/dist/FAIL.app/Contents/Resources/__boot__.py", line 342, in <module>
4/18/13 7:41:15.359 PM [0x0-0x133133].org.pythonmac.unspecified.FAIL:     _run()
4/18/13 7:41:15.359 PM [0x0-0x133133].org.pythonmac.unspecified.FAIL:   File "/Users/peachg/dist/FAIL.app/Contents/Resources/__boot__.py", line 335, in _run
4/18/13 7:41:15.359 PM [0x0-0x133133].org.pythonmac.unspecified.FAIL:     exec(compile(source, script, 'exec'), globals(), globals())
4/18/13 7:41:15.359 PM [0x0-0x133133].org.pythonmac.unspecified.FAIL:   File "/Users/peachg/FAIL.py", line 8, in <module>
4/18/13 7:41:15.360 PM [0x0-0x133133].org.pythonmac.unspecified.FAIL:     from setuptools import setup
4/18/13 7:41:15.360 PM [0x0-0x133133].org.pythonmac.unspecified.FAIL:   File "/Library/Frameworks/Python.framework/Versions/2.7/lib/python2.7/site-packages/setuptools-0.6c12dev_r88846-py2.7.egg/setuptools/__init__.py", line 2, in <module>
4/18/13 7:41:15.360 PM [0x0-0x133133].org.pythonmac.unspecified.FAIL:   File "/Library/Frameworks/Python.framework/Versions/2.7/lib/python2.7/site-packages/setuptools-0.6c12dev_r88846-py2.7.egg/setuptools/extension.py", line 2, in <module>
4/18/13 7:41:15.360 PM [0x0-0x133133].org.pythonmac.unspecified.FAIL:   File "/Library/Frameworks/Python.framework/Versions/2.7/lib/python2.7/site-packages/setuptools-0.6c12dev_r88846-py2.7.egg/setuptools/dist.py", line 5, in <module>
4/18/13 7:41:15.360 PM [0x0-0x133133].org.pythonmac.unspecified.FAIL:   File "/Library/Frameworks/Python.framework/Versions/2.7/lib/python2.7/site-packages/setuptools-0.6c12dev_r88846-py2.7.egg/setuptools/command/install.py", line 2, in <module>
4/18/13 7:41:15.360 PM [0x0-0x133133].org.pythonmac.unspecified.FAIL:   File "/Library/Frameworks/Python.framework/Versions/2.7/lib/python2.7/distutils/command/install.py", line 21, in <module>
4/18/13 7:41:15.360 PM [0x0-0x133133].org.pythonmac.unspecified.FAIL:     from site import USER_BASE
4/18/13 7:41:15.360 PM [0x0-0x133133].org.pythonmac.unspecified.FAIL: ImportError: cannot import name USER_BASE
I am really sorry if this is not the appropriate place to ask for assistance but honestly I have had this issue for around a month and am at my wits end.
Notes:
MacOSX 10.7.5
Have tried pip uninstalled then tried easy install
And installing all the dependancies separately

**Comment by ronaldoussoren** [comment]
Version 0.26 will define USER_BASE and related functions (to be released soon...)
