### ISSUE TITLE
_copy_file fails when copying a read-only file to an existing destination

### ISSUE THREAD

**Issue by ronaldoussoren** [ronaldoussoren/py2app#134]
**[Original report](https://bitbucket.org/ronaldoussoren/py2app/issue/134) by Sean Fisk (Bitbucket: [seanfisk](https://bitbucket.org/seanfisk), GitHub: [seanfisk](https://github.com/seanfisk)).**

----------------------------------------

This bug manifests when building the app bundle for our project, which uses PySide. The issue seems to be that py2app copies the QtCore framework twice, and fails the second time when it tries to write to an existing read-only file.

The problem is in the `_copy_file` function, where the file is copied by reading all the data from the source and writing it all to the destination. This issue exists in 0.8 and above, including the latest development version. It did not exist in 0.7.3, because the option to preserve the file's mode was stubbed out like so:

```python
if preserve_mode:
    # XXX: copy current mode
    pass
```

This caused the read-only file to be written with write permissions, and the `with open(destination, 'wb')` call succeeded. In newer versions, where `preserve_mode` is implemented properly, it fails.

I am not sure why the file is attempted to be copied twice; however, this problem seems orthogonal to the problem that `_copy_file` fails. The issue of the double copy is probably more deep-seated and more difficult to debug.

Here is the relevant traceback:
```
copying file /usr/local/Cellar/qt/4.8.5/lib/QtCore.framework/Contents/Info.plist -> /Users/sean/src/personal/better-banner/better-banner/dist/BetterBanner.app/Contents/Frameworks/QtCore.framework/Contents/Info.plist
Traceback (most recent call last):
  File "/Users/sean/.pyenv/versions/better-banner275/lib/python2.7/site-packages/paver/tasks.py", line 195, in _run_task
    return do_task()
  File "/Users/sean/.pyenv/versions/better-banner275/lib/python2.7/site-packages/paver/tasks.py", line 191, in do_task
    task()
  File "/Users/sean/.pyenv/versions/better-banner275/lib/python2.7/site-packages/paver/setuputils.py", line 175, in __call__
    self.distribution.run_command(self.command_name)
  File "/Users/sean/.pyenv/versions/2.7.5/lib/python2.7/distutils/dist.py", line 972, in run_command
    cmd_obj.run()
  File "/Users/sean/.pyenv/versions/better-banner275/lib/python2.7/site-packages/py2app-0.9-py2.7.egg/py2app/build_app.py", line 651, in run
    self._run()
  File "/Users/sean/.pyenv/versions/better-banner275/lib/python2.7/site-packages/py2app-0.9-py2.7.egg/py2app/build_app.py", line 857, in _run
    self.run_normal()
  File "/Users/sean/.pyenv/versions/better-banner275/lib/python2.7/site-packages/py2app-0.9-py2.7.egg/py2app/build_app.py", line 947, in run_normal
    self.create_binaries(py_files, pkgdirs, extensions, loader_files)
  File "/Users/sean/.pyenv/versions/better-banner275/lib/python2.7/site-packages/py2app-0.9-py2.7.egg/py2app/build_app.py", line 1107, in create_binaries
    platfiles = mm.run()
  File "/Users/sean/.pyenv/versions/better-banner275/lib/python2.7/site-packages/macholib/MachOStandalone.py", line 105, in run
    mm.run_file(fn)
  File "/Users/sean/.pyenv/versions/better-banner275/lib/python2.7/site-packages/macholib/MachOGraph.py", line 84, in run_file
    self.scan_node(m)
  File "/Users/sean/.pyenv/versions/better-banner275/lib/python2.7/site-packages/macholib/MachOGraph.py", line 110, in scan_node
    m = self.load_file(filename, caller=node)
  File "/Users/sean/.pyenv/versions/better-banner275/lib/python2.7/site-packages/macholib/MachOGraph.py", line 95, in load_file
    return self.load_file(newname, caller=caller)
  File "/Users/sean/.pyenv/versions/better-banner275/lib/python2.7/site-packages/macholib/MachOGraph.py", line 98, in load_file
    self.scan_node(m)
  File "/Users/sean/.pyenv/versions/better-banner275/lib/python2.7/site-packages/macholib/MachOGraph.py", line 110, in scan_node
    m = self.load_file(filename, caller=node)
  File "/Users/sean/.pyenv/versions/better-banner275/lib/python2.7/site-packages/macholib/MachOGraph.py", line 91, in load_file
    m = self.findNode(name)
  File "/Users/sean/.pyenv/versions/better-banner275/lib/python2.7/site-packages/macholib/MachOGraph.py", line 70, in findNode
    newname = self.locate(name, loader=loader)
  File "/Users/sean/.pyenv/versions/better-banner275/lib/python2.7/site-packages/macholib/MachOStandalone.py", line 26, in locate
    return self.delegate.locate(newname)
  File "/Users/sean/.pyenv/versions/better-banner275/lib/python2.7/site-packages/macholib/MachOStandalone.py", line 65, in locate
    res = self.copy_framework(info)
  File "/Users/sean/.pyenv/versions/better-banner275/lib/python2.7/site-packages/py2app-0.9-py2.7.egg/py2app/build_app.py", line 183, in copy_framework
    destfn = self.appbuilder.copy_framework(info, self.dest)
  File "/Users/sean/.pyenv/versions/better-banner275/lib/python2.7/site-packages/py2app-0.9-py2.7.egg/py2app/build_app.py", line 1248, in copy_framework
    self.copy_versioned_framework(info, dst)
  File "/Users/sean/.pyenv/versions/better-banner275/lib/python2.7/site-packages/py2app-0.9-py2.7.egg/py2app/build_app.py", line 1241, in copy_versioned_framework
    preserve_symlinks=True, condition=condition)
  File "/Users/sean/.pyenv/versions/better-banner275/lib/python2.7/site-packages/py2app-0.9-py2.7.egg/py2app/build_app.py", line 1893, in copy_tree
    condition=condition)
  File "/Users/sean/.pyenv/versions/better-banner275/lib/python2.7/site-packages/py2app-0.9-py2.7.egg/py2app/util.py", line 561, in copy_tree
    dry_run=dry_run, condition=condition))
  File "/Users/sean/.pyenv/versions/better-banner275/lib/python2.7/site-packages/py2app-0.9-py2.7.egg/py2app/util.py", line 564, in copy_tree
    preserve_times, update, dry_run=dry_run)
  File "/Users/sean/.pyenv/versions/better-banner275/lib/python2.7/site-packages/py2app-0.9-py2.7.egg/py2app/util.py", line 138, in copy_file
    _copy_file(source, destination, preserve_mode, preserve_times, update, dry_run)
  File "/Users/sean/.pyenv/versions/better-banner275/lib/python2.7/site-packages/py2app-0.9-py2.7.egg/py2app/util.py", line 151, in _copy_file
    with open(destination, 'wb') as fp_out:
IOError: [Errno 13] Permission denied: '/Users/sean/src/personal/better-banner/better-banner/dist/BetterBanner.app/Contents/Frameworks/QtCore.framework/Contents/Info.plist'
```

**Comment by ronaldoussoren** [comment]
fd5a74f2f7b831a0c360fdb079c3e17affcc8cfa fixes this by removing the destination before copying.
