### ISSUE TITLE
The 'macholib' distribution was not found and is required by the application

### ISSUE THREAD

**Issue by ronaldoussoren** [ronaldoussoren/py2app#192]
**[Original report](https://bitbucket.org/ronaldoussoren/py2app/issue/192) by Maxwell Grady (Bitbucket: [mgrady3](https://bitbucket.org/mgrady3), GitHub: [mgrady3](https://github.com/mgrady3)).**

----------------------------------------

I am trying to build an application but have been running into this error with both pyinstaller and py2app.

There are a large number of dependencies - I can list them all if needed - the main ones are numpy, scipy, matplotlib, opencv, and PIL

The py2app build process works as normal and completely finishes.

when running the application however, I get the following errors in my terminal:

```
Traceback (most recent call last):
   File "/Users/****/test-build/dist/main.app/Contents/Resources/__boot__.py", line 398, in <module>

_setup_ctypes()

File "/Users/*****/test-build/dist/main.app/Contents/Resources/__boot__.py", line 392, in _setup_ctypes

from ctypes.macholib import dyld

 File "ctypes/macholib/__init__.pyc", line 10, in <module>

File "pkg_resources/__init__.pyc", line 952, in require

File "pkg_resources/__init__.pyc", line 839, in resolve

pkg_resources.DistributionNotFound: The 'macholib' distribution was not found and is required by the application

main Error
```

I know for a fact I have macholib installed on my machine

There aren't any issues with it that I am aware of

I can open a new python prompt and type from ctypes.macholib import dyld
and it works just fine

I thought to try copying the entire /User/*****/anaconda/lib/python2.7/ctypes/macholib to my app folder but wasn't sure exactly where it would need to go other than /dist/main.app/Contents/ somewhere further buried in here

EDIT: it may be worth noting, I successfully built the same program  for Linux using pyinstaller under Ubuntu 14.

**Comment by ronaldoussoren** [comment]
Fixed by fixing #1.
