### ISSUE TITLE
Traceback "Reason: image not found" on Mac executable

### ISSUE THREAD

**Issue by ronaldoussoren** [ronaldoussoren/py2app#254]
**[Original report](https://bitbucket.org/ronaldoussoren/py2app/issue/254) by Yanone (Bitbucket: [yanone](https://bitbucket.org/yanone), GitHub: [yanone](https://github.com/yanone)).**

----------------------------------------

Hi. I'm having this issue running my wxPython-based Mac app. A few months ago it ran fine, now it doesn't, even though I'm unaware that I changed any relevant software configurations.

Running py2app 0.18
wxPython 4.0.3
MacOS 10.13.6

I don't know what to make of the following traceback when running the app:

```
#!python

Traceback (most recent call last):
  File "/Users/yanone/Code/TypeWorldApp/dist/Type.World.app/Contents/Resources/__boot__.py", line 98, in <module>
    _run()
  File "/Users/yanone/Code/TypeWorldApp/dist/Type.World.app/Contents/Resources/__boot__.py", line 82, in _run
    exec(compile(source, path, 'exec'), globals(), globals())
  File "/Users/yanone/Code/TypeWorldApp/dist/Type.World.app/Contents/Resources/app.py", line 5, in <module>
    import wx, os, webbrowser, urllib.request, urllib.parse, urllib.error, base64, plistlib, json, datetime, traceback, ctypes
  File "wx/__init__.pyc", line 17, in <module>
  File "wx/core.pyc", line 12, in <module>
  File "wx/_core.pyc", line 14, in <module>
  File "wx/_core.pyc", line 10, in __load
  File "imp.pyc", line 342, in load_dynamic
ImportError: dlopen(/Users/yanone/Code/TypeWorldApp/dist/Type.World.app/Contents/Resources/lib/python3.6/lib-dynload/wx/_core.so, 2): Library not loaded: @loader_path/libwx_osx_cocoau_core-3.0.0.4.0.dylib
  Referenced from: /Users/yanone/Code/TypeWorldApp/dist/Type.World.app/Contents/Resources/lib/python3.6/lib-dynload/wx/_core.so
  Reason: image not found
```

Happy to post any additional information if you let me know what.

Thank you.

**Comment by hamishmb** [comment]
NB: Chris, I wrote myself a little script to work around this bug and keep the bundle size smaller. See my comment on #252
