### ISSUE TITLE
issue with PIL/pillow py2app on OS X 10.14.2 & 10.14.3

### ISSUE THREAD

**Issue by ronaldoussoren** [ronaldoussoren/py2app#258]
**[Original report](https://bitbucket.org/ronaldoussoren/py2app/issue/258) by Matthew Speckman (Bitbucket: [mspeckman](https://bitbucket.org/mspeckman), ).**

----------------------------------------

having an issue freezing 

Matthews-MacBook-Pro-2:dist Matt$ Cabinet\ Searcher.app/Contents/MacOS/Cabinet\ Searcher 
Traceback (most recent call last):
  File "/Users/Matt/new_oob_project/dist/Cabinet Searcher.app/Contents/Resources/__boot__.py", line 87, in _recipes_pil_prescript
    import Image
  File "Image.pyc", line 1, in <module>
  File "PIL/Image.pyc", line 94, in <module>
  File "PIL/_imaging.pyc", line 14, in <module>
  File "PIL/_imaging.pyc", line 10, in __load
  File "imp.pyc", line 342, in load_dynamic
ImportError: dlopen(/Users/Matt/new_oob_project/dist/Cabinet Searcher.app/Contents/Resources/lib/python3.7/lib-dynload/PIL/_imaging.so, 2): Library not loaded: @loader_path/.dylibs/libjpeg.9.dylib
  Referenced from: /Users/Matt/new_oob_project/dist/Cabinet Searcher.app/Contents/Resources/lib/python3.7/lib-dynload/PIL/_imaging.so
  Reason: image not found

During handling of the above exception, another exception occurred:

Traceback (most recent call last):
  File "/Users/Matt/new_oob_project/dist/Cabinet Searcher.app/Contents/Resources/__boot__.py", line 132, in <module>
    _recipes_pil_prescript(['IcnsImagePlugin', 'BufrStubImagePlugin', 'ImImagePlugin', 'CurImagePlugin', 'GribStubImagePlugin', 'IptcImagePlugin', 'FliImagePlugin', 'Hdf5StubImagePlugin', 'TiffImagePlugin', 'PngImagePlugin', 'GifImagePlugin', 'PpmImagePlugin', 'FtexImagePlugin', 'XVThumbImagePlugin', 'SgiImagePlugin', 'XpmImagePlugin', 'FitsStubImagePlugin', 'SunImagePlugin', 'PalmImagePlugin', 'IcoImagePlugin', 'PcxImagePlugin', 'McIdasImagePlugin', 'PsdImagePlugin', 'MpoImagePlugin', 'MpegImagePlugin', 'PdfImagePlugin', 'MicImagePlugin', 'PixarImagePlugin', 'SpiderImagePlugin', 'BmpImagePlugin', 'WmfImagePlugin', 'GbrImagePlugin', 'WebPImagePlugin', 'PcdImagePlugin', 'BlpImagePlugin', 'FpxImagePlugin', 'ImtImagePlugin', 'TgaImagePlugin', 'XbmImagePlugin', 'JpegImagePlugin', 'ArgImagePlugin', 'EpsImagePlugin', 'DdsImagePlugin', 'MspImagePlugin', 'Jpeg2KImagePlugin', 'DcxImagePlugin'])
  File "/Users/Matt/new_oob_project/dist/Cabinet Searcher.app/Contents/Resources/__boot__.py", line 90, in _recipes_pil_prescript
    from PIL import Image
  File "PIL/Image.pyc", line 94, in <module>
  File "PIL/_imaging.pyc", line 14, in <module>
  File "PIL/_imaging.pyc", line 10, in __load
  File "imp.pyc", line 342, in load_dynamic
ImportError: dlopen(/Users/Matt/new_oob_project/dist/Cabinet Searcher.app/Contents/Resources/lib/python3.7/lib-dynload/PIL/_imaging.so, 2): Library not loaded: @loader_path/.dylibs/libjpeg.9.dylib
  Referenced from: /Users/Matt/new_oob_project/dist/Cabinet Searcher.app/Contents/Resources/lib/python3.7/lib-dynload/PIL/_imaging.so
  Reason: image not found
2019-01-10 15:29:52.718 Cabinet Searcher[2793:46369] Cabinet Searcher Error
Matthews-MacBook-Pro-2:dist Matt$ 

Python 3.7.2

Pillow                       5.4.1     
Pillow-PIL                   0.1.dev0  
py2app                       0.18 
macholib                     1.11 
setuptools                   40.6.3

I have tried including PIL in the includes, and tried putting pillow in the setup requires list as well...  this is a tkinter gui application.

**Comment by ydkhatri** [comment]
The workaround suggested `--packages=PIL` results in this error:
```
WARNING: Mach-O header in '/Users/yogesh/Desktop/mac_apt/dist/mac_apt_artifact_only.app/Contents/Resources/lib/python3.8/PIL/.dylibs/liblcms2.2.dylib' may be too large to relocate
Traceback (most recent call last):
  File "build/setup-mac_apt_artifact_only.py", line 27, in <module>
    setup(
  File "/Users/yogesh/Desktop/mac_apt/env/lib/python3.8/site-packages/setuptools/__init__.py", line 145, in setup
    return distutils.core.setup(**attrs)
  File "/Library/Frameworks/Python.framework/Versions/3.8/lib/python3.8/distutils/core.py", line 148, in setup
    dist.run_commands()
  File "/Library/Frameworks/Python.framework/Versions/3.8/lib/python3.8/distutils/dist.py", line 966, in run_commands
    self.run_command(cmd)
  File "/Library/Frameworks/Python.framework/Versions/3.8/lib/python3.8/distutils/dist.py", line 985, in run_command
    cmd_obj.run()
  File "/Users/yogesh/Desktop/mac_apt/env/lib/python3.8/site-packages/py2app/build_app.py", line 907, in run
    self._run()
  File "/Users/yogesh/Desktop/mac_apt/env/lib/python3.8/site-packages/py2app/build_app.py", line 1125, in _run
    self.run_normal()
  File "/Users/yogesh/Desktop/mac_apt/env/lib/python3.8/site-packages/py2app/build_app.py", line 1238, in run_normal
    self.create_binaries(py_files, pkgdirs, extensions, loader_files)
  File "/Users/yogesh/Desktop/mac_apt/env/lib/python3.8/site-packages/py2app/build_app.py", line 1629, in create_binaries
    platfiles = mm.run()
  File "/Users/yogesh/Desktop/mac_apt/env/lib/python3.8/site-packages/macholib/MachOStandalone.py", line 166, in run
    node.write(f)
  File "/Users/yogesh/Desktop/mac_apt/env/lib/python3.8/site-packages/macholib/MachO.py", line 173, in write
    header.write(f)
  File "/Users/yogesh/Desktop/mac_apt/env/lib/python3.8/site-packages/macholib/MachO.py", line 403, in write
    self.synchronize_size()
  File "/Users/yogesh/Desktop/mac_apt/env/lib/python3.8/site-packages/macholib/MachO.py", line 382, in synchronize_size
    raise ValueError(
ValueError: New Mach-O header is too large to relocate in '/Users/yogesh/Desktop/mac_apt/dist/mac_apt_artifact_only.app/Contents/Resources/lib/python3.8/PIL/.dylibs/liblcms2.2.dylib' (new size=1688, max size=1680, delta=48)
```

**Comment by jj-jitterbit** [comment]
I was able to fix this issue of the large Mach-0 header by installing Pillow from source:

       python -m pip install git+https://github.com/python-pillow/Pillow.git

after installing all the dependencies [as described on Pillow's webpage](https://pillow.readthedocs.io/en/stable/installation.html#building-on-macos). However, I skipped the step (`depends/install_raqm_cmake.sh to install libraqm`) and it seems to work fine. I had Pillow installed in an earlier version using `pip install Pillow`, so I am guessing that library was already satisfied.

**Comment by radarhere** [comment]
In https://github.com/python-pillow/Pillow/issues/4001, I came to the conclusion that 'ValueError: New Mach-O header is too large to relocate in ...liblcms2.2.dylib' is fixed for Pillow >= 7.2, presumably as a result of updating to lcms2 2.10 in the wheels

**Comment by radarhere** [comment]
Hi. 'New Mach-O header is too large to relocate' has returned to Pillow again in https://github.com/python-pillow/Pillow/issues/7250, with the release of libwebp 1.3.1. Perhaps interestingly, the error also only occurs for Python >= 3.10.

My question - glancing at https://github.com/webmproject/libwebp/compare/v1.3.0...v1.3.1, does anything jump out as being the cause of this? I'm wondering there is something hiding in that diff that can be communicated to the libwebp team as a bug.

Alternatively, I could try and step through the commits between 1.3.0 and 1.3.1 to see where it breaks, if you think you would be able to spot something in a shorter diff.

Thanks for any thoughts.
