### ISSUE TITLE
Fails to create working app when VTK is used

### ISSUE THREAD

**Issue by ronaldoussoren** [ronaldoussoren/py2app#260]
**[Original report](https://bitbucket.org/ronaldoussoren/py2app/issue/260) by Elvis Stansvik (Bitbucket: [estan](https://bitbucket.org/estan), GitHub: [estan](https://github.com/estan)).**

----------------------------------------

Reproducer:

```
(tenv) dirac:~ insight$ sw_vers 
ProductName:    Mac OS X
ProductVersion: 10.14.2
BuildVersion:   18C54
(tenv) dirac:~ insight$ pip list
Package     Version
----------- -------
altgraph    0.16.1 
macholib    1.11   
modulegraph 0.17   
pip         10.0.1 
py2app      0.18   
PyQt5       5.11.3 
PyQt5-sip   4.19.13
setuptools  39.0.1 
sip         4.19.8 
vtk         8.1.2  
You are using pip version 10.0.1, however version 19.0.1 is available.
You should consider upgrading via the 'pip install --upgrade pip' command.
(tenv) dirac:~ insight$ mkdir myapp
(tenv) dirac:~ insight$ cd myapp
(tenv) dirac:myapp insight$ echo "import vtk" > MyApplication.py
(tenv) dirac:myapp insight$ py2applet --make-setup MyApplication.py
Wrote setup.py
(tenv) dirac:myapp insight$ python setup.py py2app
.
.
.
(tenv) dirac:myapp insight$ dist/MyApplication.app/Contents/MacOS/MyApplication 
Traceback (most recent call last):
  File "vtk/vtkCommonKit.pyc", line 5, in <module>
  File "vtk/vtkCommonKitPython.pyc", line 14, in <module>
  File "vtk/vtkCommonKitPython.pyc", line 10, in __load
  File "imp.pyc", line 342, in load_dynamic
ImportError: dlopen(/Users/insight/myapp/dist/MyApplication.app/Contents/Resources/lib/python3.7/lib-dynload/vtk/vtkCommonKitPython.so, 2): Library not loaded: @loader_path/libvtkCommonKitPython37D-8.1.1.dylib
  Referenced from: /Users/insight/myapp/dist/MyApplication.app/Contents/Resources/lib/python3.7/lib-dynload/vtk/vtkCommonKitPython.so
  Reason: image not found

During handling of the above exception, another exception occurred:

Traceback (most recent call last):
  File "/Users/insight/myapp/dist/MyApplication.app/Contents/Resources/__boot__.py", line 98, in <module>
    _run()
  File "/Users/insight/myapp/dist/MyApplication.app/Contents/Resources/__boot__.py", line 82, in _run
    exec(compile(source, path, 'exec'), globals(), globals())
  File "/Users/insight/myapp/dist/MyApplication.app/Contents/Resources/MyApplication.py", line 1, in <module>
    import vtk
  File "vtk/__init__.pyc", line 7, in <module>
  File "vtk/vtkCommonKit.pyc", line 9, in <module>
ModuleNotFoundError: No module named 'vtkCommonKitPython'
2019-02-01 15:39:54.219 MyApplication[87787:7778690] MyApplication Error
```

Attaching output from `python setup.py py2app` (`py2app.log`) and `find dist` (`contents.txt`).

As you can see, the library it cannot find (`libvtkCommonKitPython37D-8.1.1.dylib`) is in `Contents/Frameworks`, where it can't be found because its dependee is in `Contents/Resources/lib/python3.7/lib-dynload/vtk` and `@loader_path` is used.

**Comment by ronaldoussoren** [comment]
This should be fixed in 2fde755a903bb9f20c3095b41f1ef4088f435690
