### ISSUE TITLE
Py2App v0.13 App not opening on second machine/ Py2App>0.13 always outputs ValueError

### ISSUE THREAD

**Issue by dallhouse** [ronaldoussoren/py2app#294]
So I finally got my python program working on my Mac (Catalina 10.15.4), but I am greeted with the following error when it is opened on another Mac (High Sierra 10.13.6.) 
```
Could not import the PyAudio C module '_portaudio'.
Traceback (most recent call last):
  File "/Volumes/dist/Riff Gen.app/Contents/Resources/__boot__.py", line 355, in <module>
    _run()
  File "/Volumes/dist/Riff Gen.app/Contents/Resources/__boot__.py", line 340, in _run
    exec(compile(source, path, 'exec'), globals(), globals())
  File "/Volumes/dist/Riff Gen.app/Contents/Resources/riffgen_v1.01.py", line 9, in <module>
    from pysine import sine
  File "pysine/__init__.pyc", line 14, in <module>
  File "pysine/pysine.pyc", line 1, in <module>
  File "pyaudio.pyc", line 116, in <module>
ImportError: dlopen(/Volumes/dist/Riff Gen.app/Contents/Resources/lib/python3.6/lib-dynload/_portaudio.so, 2): Symbol not found: ____chkstk_darwin
  Referenced from: /Volumes/dist/Riff Gen.app/Contents/MacOS/../Frameworks/libportaudio.2.dylib (which was built for Mac OS X 10.15)
  Expected in: /usr/lib/libSystem.B.dylib
 in /Volumes/dist/Riff Gen.app/Contents/MacOS/../Frameworks/libportaudio.2.dylib
```

A simple tkinter test with various sounds and images works fine on the second machine, but not this script. I've tried adding all the packages manually, tried --nostrip, manually including 'libportaudio.2.dylib', and dozens of other ideas from countless outdated forums to no avail. 

I have been using Python 3.6 and Py2App v0.13 because it is, unfortunately, the _only_ version that has successfully packaged my program in a standalone package. Any version later than 0.13 gives me the following error _even_ when bundling in alias mode:
```
Traceback (most recent call last):
  File "/Users/Alex/Desktop/python_scripts/rhythm_generator/riffgen/dist/Riff Gen.app/Contents/Resources/__boot__.py", line 420, in <module>
    _run()
  File "/Users/Alex/Desktop/python_scripts/rhythm_generator/riffgen/dist/Riff Gen.app/Contents/Resources/__boot__.py", line 414, in _run
    exec(compile(source, script, 'exec'), globals(), globals())
  File "/Users/Alex/Desktop/python_scripts/rhythm_generator/riffgen/riffgen_v1.01.py", line 7, in <module>
    from tkinter import *
  File "/Library/Frameworks/Python.framework/Versions/3.6/lib/python3.6/tkinter/__init__.py", line 36, in <module>
    import _tkinter # If this fails your Python may not be configured for Tk
ValueError: character U+6573552f is not in range [U+0000; U+10ffff]
```

I've seen a handful of people with similar errors to the one above, but the few solutions I've seen had no success.

I'm assuming there is a simple solution to both of these errors, but after a long 10 days of tinkering, I'm out of ideas. I just began programming and _really_ want to continue to deploy GUI programs, so I am desperate to get this functional. Any help is **greatly** appreciated!!

**Comment by ronaldoussoren** [comment]
The problem is that ``libportaudio.2.dylib`` (which is used by our application) is build with a deployment target of 10.15 and uses symbols that aren't available on macOS 10.13.   There's nothing I can do about this, other than possibly adding an option to specify the deployment target for the application and warn about issues like this.

You'll have to rebuild the python package that includes this dylib with the correct deployment target. The easiest way to do so is to build this package on a 10.13 machine.
