### ISSUE TITLE
DistributionNotFound: The 'google-api-core' distribution was not found

### ISSUE THREAD

**Issue by paco020295** [ronaldoussoren/py2app#311]
Maybe this is not related at all, but i want to mention it. I created an executable file for this Python script in windows using Pyinstaller. And i had a similar issue. I fixed it by doing this: https://stackoverflow.com/a/59343195
Adding the metadata to the hook folder. But i am not sure how to reproduce this on Mac and in py2app.

This is the Traceback error when running the application:

```
Traceback (most recent call last):
  File "/Users/alba/Desktop/superpancho/dist/gui.app/Contents/Resources/__boot__.py", line 101, in <module>
    _run()
  File "/Users/alba/Desktop/superpancho/dist/gui.app/Contents/Resources/__boot__.py", line 84, in _run
    exec(compile(source, path, "exec"), globals(), globals())
  File "/Users/alba/Desktop/superpancho/dist/gui.app/Contents/Resources/gui.py", line 7, in <module>
    from scraper import main
  File "<frozen importlib._bootstrap>", line 991, in _find_and_load
  File "<frozen importlib._bootstrap>", line 975, in _find_and_load_unlocked
  File "<frozen importlib._bootstrap>", line 655, in _load_unlocked
  File "<frozen importlib._bootstrap>", line 618, in _load_backward_compatible
  File "<frozen zipimport>", line 259, in load_module
  File "scraper.pyc", line 7, in <module>
  File "<frozen importlib._bootstrap>", line 991, in _find_and_load
  File "<frozen importlib._bootstrap>", line 975, in _find_and_load_unlocked
  File "<frozen importlib._bootstrap>", line 655, in _load_unlocked
  File "<frozen importlib._bootstrap>", line 618, in _load_backward_compatible
  File "<frozen zipimport>", line 259, in load_module
  File "apiclient/__init__.pyc", line 8, in <module>
  File "<frozen importlib._bootstrap>", line 991, in _find_and_load
  File "<frozen importlib._bootstrap>", line 975, in _find_and_load_unlocked
  File "<frozen importlib._bootstrap>", line 655, in _load_unlocked
  File "<frozen importlib._bootstrap>", line 618, in _load_backward_compatible
  File "<frozen zipimport>", line 259, in load_module
  File "googleapiclient/discovery.pyc", line 50, in <module>
  File "<frozen importlib._bootstrap>", line 991, in _find_and_load
  File "<frozen importlib._bootstrap>", line 975, in _find_and_load_unlocked
  File "<frozen importlib._bootstrap>", line 655, in _load_unlocked
  File "<frozen importlib._bootstrap>", line 618, in _load_backward_compatible
  File "<frozen zipimport>", line 259, in load_module
  File "google/api_core/__init__.pyc", line 23, in <module>
  File "pkg_resources/__init__.pyc", line 465, in get_distribution
  File "pkg_resources/__init__.pyc", line 341, in get_provider
  File "pkg_resources/__init__.pyc", line 884, in require
  File "pkg_resources/__init__.pyc", line 770, in resolve
pkg_resources.DistributionNotFound: The 'google-api-core' distribution was not found and is required by the application
2020-10-01 13:56:32.664 gui[34947:1068756] gui Error
```

**Comment by simoncozens** [comment]
I have a similar error with an app which uses the `munch` library. `munch` gets its version like so:

```
__version__ = pkg_resources.get_distribution('munch').version
```

But as there is no distribution (even if I put the library name into `includes` in the config), loading the library fails.

**Comment by ronaldoussoren** [comment]
py2app currently does not copy distribution metadata into the application bundle.

**Comment by ronaldoussoren** [comment]
The relevant issue is #1, which I fixed earlier today. This will work correctly in py2app 0.26 (to be released soon...)
