### ISSUE TITLE
Py2App v0.21 App is not launching just ask if I want to terminate the app or open console.

### ISSUE THREAD

**Issue by RaviMengar** [ronaldoussoren/py2app#312]
Hi,

Working in Mac OS X Catalina 10.15.6 with python 3.8

I've coded a **python3.8** app with **PyQt5**. It's working perfectly with python3 main.py, and even When using the alias mode of py2app (python main.py py2app -A) the application runs perfectly.
Now, I create the final standalone (python main.py py2app) and the output app runs perfectly.

Now, when I try to run this app in **another mac**, _the application is not launching instead it asks if I want to terminate the app or open console_.
 
Maybe, It looks like the app cannot find things in their proper place or It may have some packaging issue.

Any help really appreciated!

**Comment by ffjdm** [comment]
Hi, I had a simiilar issue. The app couldn't find my data files and thus popping an exception. Did you double-check all data files were available?

**Comment by RaviMengar** [comment]
> 
> 
> Hi, I had a simiilar issue. The app couldn't find my data files and thus popping an exception. Did you double-check all data files were available?

@ffjdm I have checked all data files although having this issue.

**Comment by 26huitailang** [comment]
OS: Mac OS X Catalina 10.15.7
Python: python3.8

The same problem. But it works in macOS 11 Big Sur with python38/python39. [a popclip plugin](https://github.com/rexzhang/trans-pad)

**Comment by rexzhang** [comment]
i had the some problem.

macOS 10.14.6
py38/py39
py2app 0.22

project: https://github.com/rexzhang/trans-pad

**Comment by rexzhang** [comment]
maybe it's ABI compatibility problems. build on macOS 11, run it on 11.14
```
Last login: Tue Jan  5 22:41:38 on ttys001
macOS1114:~ rex$ /Applications/TransPad.app/Contents/MacOS/TransPad ; exit;
Traceback (most recent call last):
  File "/Applications/TransPad.app/Contents/Resources/__boot__.py", line 411, in <module>
    _run()
  File "/Applications/TransPad.app/Contents/Resources/__boot__.py", line 394, in _run
    exec(compile(source, path, "exec"), globals(), globals())
  File "/Applications/TransPad.app/Contents/Resources/TransPad.py", line 1, in <module>
    import logging.config
  File "<frozen zipimport>", line 259, in load_module
  File "logging/config.pyc", line 30, in <module>
  File "<frozen zipimport>", line 259, in load_module
  File "logging/handlers.pyc", line 26, in <module>
  File "<frozen zipimport>", line 259, in load_module
  File "socket.pyc", line 52, in <module>
  File "<frozen zipimport>", line 259, in load_module
  File "selectors.pyc", line 12, in <module>
ImportError: dlopen(/Applications/TransPad.app/Contents/Resources/lib/python3.8/lib-dynload/select.so, 2): Symbol not found: ___darwin_check_fd_set_overflow
  Referenced from: /Applications/TransPad.app/Contents/Resources/lib/python3.8/lib-dynload/select.so (which was built for Mac OS X 11.0)
  Expected in: /usr/lib/libSystem.B.dylib
 in /Applications/TransPad.app/Contents/Resources/lib/python3.8/lib-dynload/select.so
2021-01-05 23:06:21.684 TransPad[860:23769] TransPad Error
logout
Saving session...
...copying shared history...
...saving history...truncating history files...
...completed.

[进程已完成]
```

**Comment by rexzhang** [comment]
I found a solution for my own problem.

I was using python installed via brew, and now I installed a new python environment using the installer I downloaded from python.org. like `/Library/Frameworks/Python.framework/Versions/3.8/bin/python3 -m venv venv`

Repackaged the program in this environment. It works fine under macOS 10.14/10.15.

My development environment is: macOS 11.1

**Comment by rexzhang** [comment]
Maybe it's just a crop(stripping) failure?
```
stripping zlib.so
stripping _codecs_kr.so
strerror: [Errno 35] write could not complete without blocking
Exception ignored in: <_io.TextIOWrapper name='<stdout>' mode='w' encoding='utf-8'>
BlockingIOError: [Errno 35] write could not complete without blocking
ipping _lzma.so
```

**Comment by ronaldoussoren** [comment]
To build an app that runs on older versions of the OS you need a copy of Python that can run on that OS.  The easiest way to accomplish that is by using the Python.org installers that run on macOS 10.9 or later.   AFAIK most other options, such as homebrew and conda compile for more recent versions (when they offer binary downloads) or the current machine.
