### ISSUE TITLE
ImportError: dlopen(.../Contents/Resources/lib/python3.9/wx/_core.cpython-39-darwin.so, 2): bad rebase type 4 in .../Contents/MacOS/../Frameworks/liblzma.5.dylib

### ISSUE THREAD

**Issue by Deuchnord** [ronaldoussoren/py2app#317]
I'm trying to package my wxPython application, but facing the following error when trying to execute it:

```
Traceback (most recent call last):
  File "/Users/jerome/workspace/kosmorro/kosmorro/dist/Kosmorro.app/Contents/Resources/__boot__.py", line 101, in <module>
    _run()
  File "/Users/jerome/workspace/kosmorro/kosmorro/dist/Kosmorro.app/Contents/Resources/__boot__.py", line 84, in _run
    exec(compile(source, path, "exec"), globals(), globals())
  File "/Users/jerome/workspace/kosmorro/kosmorro/dist/Kosmorro.app/Contents/Resources/kosmorro-gui", line 3, in <module>
    from kosmorrolib.gui import mainwindow
  File "<frozen zipimport>", line 259, in load_module
  File "kosmorrolib/gui/mainwindow.pyc", line 2, in <module>
  File "/Users/jerome/workspace/kosmorro/kosmorro/dist/Kosmorro.app/Contents/Resources/lib/python3.9/wx/__init__.py", line 17, in <module>
    from wx.core import *
  File "/Users/jerome/workspace/kosmorro/kosmorro/dist/Kosmorro.app/Contents/Resources/lib/python3.9/wx/core.py", line 12, in <module>
    from ._core import *
ImportError: dlopen(/Users/jerome/workspace/kosmorro/kosmorro/dist/Kosmorro.app/Contents/Resources/lib/python3.9/wx/_core.cpython-39-darwin.so, 2): bad rebase type 4 in /Users/jerome/workspace/kosmorro/kosmorro/./dist/Kosmorro.app/Contents/MacOS/../Frameworks/liblzma.5.dylib
2020-11-29 12:10:31.929 kosmorro[4138:95553] Kosmorro Error
```

My `setup.py`:

```python
#!/usr/bin/env python3

from setuptools import setup


APP = ['kosmorro-gui']
DATA_FILES = []
OPTIONS = {
    'plist': 'build/distrib/darwin/Info.plist',
    'packages': ','.join(['skyfield>=1.21.0,<2.0.0', 'tabulate', 'numpy>=1.17.0,<2.0.0',
                          'termcolor', 'python-dateutil', 'wx'])
}

setup(
    app=APP,
    data_files=DATA_FILES,
    options={'py2app': OPTIONS},
    setup_requires=['py2app'],
)
```

My `kosmorro-gui`:

```python
#!/usr/bin/python3

from kosmorrolib.gui import mainwindow


def main():
    mainwindow.start()


if __name__ == '__main__':
    main()
```

`kosmorrolib` is a package included in my app.
If needed, the `mainwindow` module can be found [here](https://github.com/Kosmorro/kosmorro/blob/0f0f16676611c65fe0f523a6962fad29048f264a/kosmorrolib/gui/mainwindow.py).

I'm running macOS 11.0.1 and Python 3.9.0

What does this error mean, and how can I fix it?

**Comment by hasii2011** [comment]
I'd like to know the answer to this one also.

**Comment by ronaldoussoren** [comment]
I'll see if I can reproduce this locally. 

How did you install Python and wxPython (python.org installer, homebrew, ...)?

**Comment by hasii2011** [comment]
For me I use pyenv from homebrew;  Then create a virtual environment like 

```
python3 -m venv venv-pyenv-3.9.0 and 
source ./venv-pyenv-3.9.0/bin/activate
pip3 install wxpython
```


the latest stable wxpython

**Comment by Deuchnord** [comment]
On my side, it is installed globally with PIP:
```
pip install -g wxPython
```

**Comment by Deuchnord** [comment]
Hi @ronaldoussoren, did you manage to reproduce the error, or do you need more information? 🙂
