### ISSUE TITLE
ValueError due to missing libpython*.dylib even though libpython*m.dylib exists

### ISSUE THREAD

**Issue by albertosottile** [ronaldoussoren/py2app#325]
**NOTE**: I am not 100% sure this is an issue with py2app. Please close it if you deem it is not.

I experienced this with GitHub Actions `macos-10.15` image a few days ago. py2app fails to build with the following error ([build log](https://github.com/albertosottile/syncplay/runs/1581821315)):
```python
copying file /Users/runner/hostedtoolcache/Python/3.7.9/x64/bin/python3 -> /Users/runner/work/syncplay/syncplay/dist/Syncplay.app/Contents/MacOS/python
Traceback (most recent call last):
  File "buildPy2app.py", line 43, in <module>
    setup_requires=['py2app'],
  File "/Users/runner/hostedtoolcache/Python/3.7.9/x64/lib/python3.7/site-packages/setuptools/__init__.py", line 144, in setup
    return distutils.core.setup(**attrs)
  File "/Users/runner/hostedtoolcache/Python/3.7.9/x64/lib/python3.7/distutils/core.py", line 148, in setup
    dist.run_commands()
  File "/Users/runner/hostedtoolcache/Python/3.7.9/x64/lib/python3.7/distutils/dist.py", line 966, in run_commands
    self.run_command(cmd)
  File "/Users/runner/hostedtoolcache/Python/3.7.9/x64/lib/python3.7/distutils/dist.py", line 985, in run_command
    cmd_obj.run()
  File "/Users/runner/hostedtoolcache/Python/3.7.9/x64/lib/python3.7/site-packages/py2app/build_app.py", line 907, in run
    self._run()
  File "/Users/runner/hostedtoolcache/Python/3.7.9/x64/lib/python3.7/site-packages/py2app/build_app.py", line 1125, in _run
    self.run_normal()
  File "/Users/runner/hostedtoolcache/Python/3.7.9/x64/lib/python3.7/site-packages/py2app/build_app.py", line 1238, in run_normal
    self.create_binaries(py_files, pkgdirs, extensions, loader_files)
  File "/Users/runner/hostedtoolcache/Python/3.7.9/x64/lib/python3.7/site-packages/py2app/build_app.py", line 1622, in create_binaries
    mm.mm.run_file(runtime)
  File "/Users/runner/hostedtoolcache/Python/3.7.9/x64/lib/python3.7/site-packages/macholib/MachOGraph.py", line 89, in run_file
    raise ValueError("%r does not exist" % (pathname,))
ValueError: '/Users/runner/hostedtoolcache/Python/3.7.9/x64/lib/libpython3.7.dylib' does not exist
```

Indeed, the image does not contain this file but only `libpython3.7m.dylib`. Details:
```python
> python3 -c 'from distutils.sysconfig import get_config_var; print(get_config_var("LDLIBRARY"))'
libpython3.7m.dylib
> ls -al /Users/runner/hostedtoolcache/Python/3.7.9/x64/lib/*.dylib
-r-xr-xr-x  1 runner  staff  4169776 Dec 13 02:42 /Users/runner/hostedtoolcache/Python/3.7.9/x64/lib/libpython3.7m.dylib
```

The people at GitHub Action say that they are compiling Python [with the right flags](https://github.com/actions/virtual-environments/issues/125) and indeed they do get a framework and a shared dylib. However, for some reason they are not getting the base filename without the `m` that py2app is looking for.

I could not find any information about the "nominal" names of libpython on macOS so I am not 100% sure of where the bug is. However, from the linked issue on GitHub Actions, it seems that the m-version of the dylib was sufficient to deem the issue fixed. So, I suspect that other linkers behave well with just that library. Hence, I decided to open an issue here. Once again, if you think this is a problem on their side and that they should provide the m-less symlink, just feel free to comment and close this issue.

Side note workaround: creating a correctly named and placed [symlink](https://github.com/albertosottile/syncplay/commit/f3aefc19dfc43fd105448a0ff1422daced0803ed) effectively [solves the issue](https://github.com/albertosottile/syncplay/runs/1581869984).

**Comment by ronaldoussoren** [comment]
The traceback suggests that "something" in the app bundle is linked to "libpython3.7.dylib", even though that file does not exist.  There's two things I don't understand about that:

1. In a framework build nothing in the Python installation itself should link to libpython*.dylib, everything is linked to the framework (and libpython*dylib is just a symlink to the shared lib in the framework).
2. Extensions should not link to libpython (at least not on unix-y platforms, Windows might be different) as that's asking for problems with duplicate symbols, especially on macOS with 2-level namespaces.

Do you know if there's a way to get a copy of the python installation in the GH runner?  I'm not really interested in debugging an issue like this through the CI, the code is too complicated for that.


P.S. Am I right to assume that this affects building Syncplay with Github Actions?

**Comment by albertosottile** [comment]
> The traceback suggests that "something" in the app bundle is linked to "libpython3.7.dylib", even though that file does not exist.

The bundle contains a lot of stuff so, it might be difficult to identify the culprit. Would building the bundle with some verbose flag be more helpful?

> Do you know if there's a way to get a copy of the python installation in the GH runner? I'm not really interested in debugging an issue like this through the CI, the code is too complicated for that.

I think this is the copy of Python that I am using in the image at the moment: https://github.com/actions/python-versions/blob/50aa2873fcddf50a06faa00000fbc2299c1c3e90/versions-manifest.json#L839 . To find it, I went through the `setup-python` action source code so, I am not 100% sure.

> P.S. Am I right to assume that this affects building Syncplay with Github Actions?

Yes, you are right, but the effect is actually minimal since creating the symlink solves the issue.

**Comment by typoman** [comment]
FWIW I get the same error with py2app on OSX Catalina when I try to build pyobjc example located in: `pyobjc/pyobjc-framework-Cocoa/Examples/AppKit/CocoaBindings/ControlledPreferences`.
