### ISSUE TITLE
ImportError: No module named sip

### ISSUE THREAD

**Issue by huhuang03** [ronaldoussoren/py2app#330]
I run`python3 setup.py py2app` and the error:
```
Traceback (most recent call last):
  File "/Users/th/source/duomai/send_email.py/setup.py", line 14, in <module>
    setup(
  File "/usr/local/lib/python3.9/site-packages/setuptools/__init__.py", line 153, in setup
    return distutils.core.setup(**attrs)
  File "/usr/local/Cellar/python@3.9/3.9.0_5/Frameworks/Python.framework/Versions/3.9/lib/python3.9/distutils/core.py", line 148, in setup
    dist.run_commands()
  File "/usr/local/Cellar/python@3.9/3.9.0_5/Frameworks/Python.framework/Versions/3.9/lib/python3.9/distutils/dist.py", line 966, in run_commands
    self.run_command(cmd)
  File "/usr/local/Cellar/python@3.9/3.9.0_5/Frameworks/Python.framework/Versions/3.9/lib/python3.9/distutils/dist.py", line 985, in run_command
    cmd_obj.run()
  File "/usr/local/lib/python3.9/site-packages/py2app/build_app.py", line 925, in run
    self._run()
  File "/usr/local/lib/python3.9/site-packages/py2app/build_app.py", line 1147, in _run
    self.run_normal()
  File "/usr/local/lib/python3.9/site-packages/py2app/build_app.py", line 1244, in run_normal
    self.process_recipes(mf, filters, flatpackages, loader_files)
  File "/usr/local/lib/python3.9/site-packages/py2app/build_app.py", line 1099, in process_recipes
    rval = check(self, mf)
  File "/usr/local/lib/python3.9/site-packages/py2app/recipes/sip.py", line 111, in check
    mf.import_hook("sip", m)
  File "/usr/local/lib/python3.9/site-packages/modulegraph/modulegraph.py", line 1114, in import_hook
    q, tail = self._find_head_package(parent, name, level)
  File "/usr/local/lib/python3.9/site-packages/modulegraph/modulegraph.py", line 1215, in _find_head_package
    raise ImportError("No module named " + qname)
ImportError: No module named sip
```

And my setup.py
``` python
"""
This is a setup.py script generated by py2applet

Usage:
    python setup.py py2app
"""

from setuptools import setup

APP = ['cli.py']
DATA_FILES = []
OPTIONS = {}

setup(
    app=APP,
    data_files=DATA_FILES,
    options={'py2app': OPTIONS},
    setup_requires=['py2app'],
)
```

It's seems like qt relative. But I didn't used qt, I just use the tkinter...

The detail log is long, I create an attach. https://www.dropbox.com/s/4pcc9zv7dgoq37j/log.txt?dl=0

How to fix this?

**Comment by denisgl7** [comment]
how did you solve the problem?

**Comment by huhuang03** [comment]
I didn't. and I didn't need it now.

**Comment by k3an3** [comment]
I believe you need to include the package:

```python
OPTIONS = {
    'packages': ['sip'],
}
```
Or if the `sip` package is named something else, use the real name of the package.

**Comment by huhuang03** [comment]
Ok, I will close this, If any still need, please reopen.

**Comment by ronaldoussoren** [comment]
Do you use PyQt or some other package that uses the "sip" tool.

The error seems to indicate that py2app detects a partial installation of sip (there is enough there to detect that sip is used, but the sip module is not present).
