### ISSUE TITLE
py2app doesn't handle more than one file with the name __init__

### ISSUE THREAD

**Issue by brukberhane** [ronaldoussoren/py2app#339]
To elaborate, I'm trying to package an app that uses `pydantic` as a dependency but I keep getting an error as follows:

```
Traceback (most recent call last):
  File "setup-native.py", line 17, in <module>
    setup(
  File "/Users/user/.virtualenvs/jellyfin-desktop/lib/python3.8/site-packages/setuptools/__init__.py", line 153, in setup
    return distutils.core.setup(**attrs)
  File "/Applications/Xcode.app/Contents/Developer/Library/Frameworks/Python3.framework/Versions/3.8/lib/python3.8/distutils/core.py", line 148, in setup
    dist.run_commands()
  File "/Applications/Xcode.app/Contents/Developer/Library/Frameworks/Python3.framework/Versions/3.8/lib/python3.8/distutils/dist.py", line 966, in run_commands
    self.run_command(cmd)
  File "/Applications/Xcode.app/Contents/Developer/Library/Frameworks/Python3.framework/Versions/3.8/lib/python3.8/distutils/dist.py", line 985, in run_command
    cmd_obj.run()
  File "/Users/user/.virtualenvs/jellyfin-desktop/lib/python3.8/site-packages/py2app/build_app.py", line 925, in run
    self._run()
  File "/Users/user/.virtualenvs/jellyfin-desktop/lib/python3.8/site-packages/py2app/build_app.py", line 1147, in _run
    self.run_normal()
  File "/Users/user/.virtualenvs/jellyfin-desktop/lib/python3.8/site-packages/py2app/build_app.py", line 1260, in run_normal
    self.create_binaries(py_files, pkgdirs, extensions, loader_files)
  File "/Users/user/.virtualenvs/jellyfin-desktop/lib/python3.8/site-packages/py2app/build_app.py", line 1522, in create_binaries
    byte_compile(
  File "/Users/user/.virtualenvs/jellyfin-desktop/lib/python3.8/site-packages/py2app/util.py", line 497, in byte_compile
    raise RuntimeError("Don't know how to handle %r" % mod.filename)
RuntimeError: Don't know how to handle '/Users/user/.virtualenvs/jellyfin-desktop/lib/python3.8/site-packages/pydantic/__init__'
```

**Comment by brukberhane** [comment]
The two files that start with `__init__` in the pydantic site-packages folder are `__init__.py` and `__init__.cpython-38-darwin.so`

**Comment by ronaldoussoren** [comment]
I can reproduce the problem. 

This seems to be a problem in modulegraph, there should be an extension at the end of the filename for ``pydantic.__init__`` as there is for other modules. 

Raw logging:

```
find_head_package None 'pydantic' 0
  import_module 'pydantic' 'pydantic' None
    load_module 'pydantic' None '/Users/ronald/Projects/py2app/workenv/lib/python3.9/site-packages/pydantic'
      load_package 'pydantic' '/Users/ronald/Projects/py2app/workenv/lib/python3.9/site-packages/pydantic' []
        addNode Package('pydantic',)
        find __init__ for ['/Users/ronald/Projects/py2app/workenv/lib/python3.9/site-packages/pydantic'] 
        load __init__ for ['/Users/ronald/Projects/py2app/workenv/lib/python3.9/site-packages/pydantic'] 
        load_module 'pydantic' None '/Users/ronald/Projects/py2app/workenv/lib/python3.9/site-packages/pydantic/__init__'
          load_package 'pydantic' '/Users/ronald/Projects/py2app/workenv/lib/python3.9/site-packages/pydantic/__init__' []
            find __init__ for ['/Users/ronald/Projects/py2app/workenv/lib/python3.9/site-packages/pydantic/__init__'] 
          load_package -> Package('pydantic', '/Users/ronald/Projects/py2app/workenv/lib/python3.9/site-packages/pydantic/__init__', ['/Users/ronald/Projects/py2app/workenv/lib/python3.9/site-packages/pydantic/__init__'])
        load_module -> Package('pydantic', '/Users/ronald/Projects/py2app/workenv/lib/python3.9/site-packages/pydantic/__init__', ['/Users/ronald/Projects/py2app/workenv/lib/python3.9/site-packages/pydantic/__init__'])
      load_package -> Package('pydantic', '/Users/ronald/Projects/py2app/workenv/lib/python3.9/site-packages/pydantic/__init__', ['/Users/ronald/Projects/py2app/workenv/lib/python3.9/site-packages/pydantic/__init__'])
    load_module -> Package('pydantic', '/Users/ronald/Projects/py2app/workenv/lib/python3.9/site-packages/pydantic/__init__', ['/Users/ronald/Projects/py2app/workenv/lib/python3.9/site-packages/pydantic/__init__'])
  import_module -> Package('pydantic', '/Users/ronald/Projects/py2app/workenv/lib/python3.9/site-packages/pydantic/__init__', ['/Users/ronald/Projects/py2app/workenv/lib/python3.9/site-packages/pydantic/__init__'])
find_head_package -> (Package('pydantic', '/Users/ronald/Projects/py2app/workenv/lib/python3.9/site-packages/pydantic/__init__', ['/Users/ronald/Projects/py2app/workenv/lib/python3.9/site-packages/pydantic/__init__']), '')
```

**Comment by ronaldoussoren** [comment]
I've added a recipe for pydantic that fixes this issue. 

The recipe doesn't fix the problem mentioned earlier, but just includes all of pydantic outside of site-packages.zip a side effect of which is fixing the build-time crash. A recipe is needed anyway because pydantic uses Cython and hides imports from the dependency analyser.
