### ISSUE TITLE
Not working with Python 3.9.2 on Big Sur

### ISSUE THREAD

**Issue by cmcknight** [ronaldoussoren/py2app#342]
Crashes when trying to build.

iMac
MacOS 11.2.3 (Big Sur)
Python 3.9.2 (from [python.org](https://python.org)

Stack Trace:

creating /Volumes/ProjectsDrive/git-projects/PyDevMgr/src/build
creating /Volumes/ProjectsDrive/git-projects/PyDevMgr/src/build/bdist.macosx-10.9-x86_64
creating /Volumes/ProjectsDrive/git-projects/PyDevMgr/src/build/bdist.macosx-10.9-x86_64/python3.9-standalone
creating /Volumes/ProjectsDrive/git-projects/PyDevMgr/src/build/bdist.macosx-10.9-x86_64/python3.9-standalone/app
creating /Volumes/ProjectsDrive/git-projects/PyDevMgr/src/build/bdist.macosx-10.9-x86_64/python3.9-standalone/app/collect
creating /Volumes/ProjectsDrive/git-projects/PyDevMgr/src/build/bdist.macosx-10.9-x86_64/python3.9-standalone/app/temp
creating /Volumes/ProjectsDrive/git-projects/PyDevMgr/src/dist
creating build/bdist.macosx-10.9-x86_64/python3.9-standalone/app/lib-dynload
creating build/bdist.macosx-10.9-x86_64/python3.9-standalone/app/Frameworks
Traceback (most recent call last):
  File "/Volumes/ProjectsDrive/git-projects/PyDevMgr/src/setup.py", line 14, in <module>
    setup(
  File "/Volumes/ProjectsDrive/git-projects/PyDevMgr/venv/lib/python3.9/site-packages/setuptools/__init__.py", line 153, in setup
    return distutils.core.setup(**attrs)
  File "/Library/Frameworks/Python.framework/Versions/3.9/lib/python3.9/distutils/core.py", line 148, in setup
    dist.run_commands()
  File "/Library/Frameworks/Python.framework/Versions/3.9/lib/python3.9/distutils/dist.py", line 966, in run_commands
    self.run_command(cmd)
  File "/Library/Frameworks/Python.framework/Versions/3.9/lib/python3.9/distutils/dist.py", line 985, in run_command
    cmd_obj.run()
  File "/Volumes/ProjectsDrive/git-projects/PyDevMgr/venv/lib/python3.9/site-packages/py2app/build_app.py", line 911, in run
    self.initialize_plist()
  File "/Volumes/ProjectsDrive/git-projects/PyDevMgr/venv/lib/python3.9/site-packages/py2app/build_app.py", line 1041, in initialize_plist
    plist["CFBundleIconFile"] = os.path.basename(iconfile)
  File "/Library/Frameworks/Python.framework/Versions/3.9/lib/python3.9/posixpath.py", line 142, in basename
    p = os.fspath(p)
TypeError: expected str, bytes or os.PathLike object, not bool

**Comment by ronaldoussoren** [comment]
What's the setup.py file used?  In particular, does it contain a setting for "iconfile" and if so, what is it?

**Comment by ronaldoussoren** [comment]
Closing this because this is likely a configuration error.
