### ISSUE TITLE
Big Sur bundle format unrecognized, invalid, or unsuitable

### ISSUE THREAD

**Issue by erichorwitz** [ronaldoussoren/py2app#344]
py2app crashes during bundle

replacing existing signature
bundle format unrecognized, invalid, or unsuitable

stack trace:

In subcomponent: /build/myapp/dist/myapp.app/Contents/Frameworks/QtRemoteObjects.framework
Traceback (most recent call last):
  File "/build/myapp/setup.py", line 14, in <module>
    setup(
  File "/opt/local/Library/Frameworks/Python.framework/Versions/3.9/lib/python3.9/site-packages/setuptools/__init__.py", line 153, in setup
    return distutils.core.setup(**attrs)
  File "/opt/local/Library/Frameworks/Python.framework/Versions/3.9/lib/python3.9/distutils/core.py", line 148, in setup
    dist.run_commands()
  File "/opt/local/Library/Frameworks/Python.framework/Versions/3.9/lib/python3.9/distutils/dist.py", line 966, in run_commands
    self.run_command(cmd)
  File "/opt/local/Library/Frameworks/Python.framework/Versions/3.9/lib/python3.9/distutils/dist.py", line 985, in run_command
    cmd_obj.run()
  File "/opt/local/Library/Frameworks/Python.framework/Versions/3.9/lib/python3.9/site-packages/py2app-0.24-py3.9.egg/py2app/build_app.py", line 925, in run
    self._run()
  File "/opt/local/Library/Frameworks/Python.framework/Versions/3.9/lib/python3.9/site-packages/py2app-0.24-py3.9.egg/py2app/build_app.py", line 1147, in _run
    self.run_normal()
  File "/opt/local/Library/Frameworks/Python.framework/Versions/3.9/lib/python3.9/site-packages/py2app-0.24-py3.9.egg/py2app/build_app.py", line 1260, in run_normal
    self.create_binaries(py_files, pkgdirs, extensions, loader_files)
  File "/opt/local/Library/Frameworks/Python.framework/Versions/3.9/lib/python3.9/site-packages/py2app-0.24-py3.9.egg/py2app/build_app.py", line 1663, in create_binaries
    codesign_adhoc(target.appdir)
  File "/opt/local/Library/Frameworks/Python.framework/Versions/3.9/lib/python3.9/site-packages/py2app-0.24-py3.9.egg/py2app/util.py", line 831, in codesign_adhoc
    _dosign(bundle)
  File "/opt/local/Library/Frameworks/Python.framework/Versions/3.9/lib/python3.9/site-packages/py2app-0.24-py3.9.egg/py2app/util.py", line 786, in _dosign
    subprocess.check_call(
  File "/opt/local/Library/Frameworks/Python.framework/Versions/3.9/lib/python3.9/subprocess.py", line 373, in check_call
    raise CalledProcessError(retcode, cmd)
subprocess.CalledProcessError: Command '('codesign', '-s', '-', '--preserve-metadata=identifier,entitlements,flags,runtime', '-f', '/build/myapp/dist/myapp.app')' returned non-zero exit status 1.

**Comment by MCMi460** [comment]
I have this issue as well. It only occurs when I try to include PyQt5 in my script.
I'm running py2app on Apple Silicon, so that might affect the results.

**Comment by ronaldoussoren** [comment]
How did you install PyQt5? The project only publishes x86_64 wheels on PyPI.

**Comment by MCMi460** [comment]
I installed it through brew, so it's possible there is some incompatibility here between architectures as PyQt5 from brew is arm64 (I believe).

**Comment by ronaldoussoren** [comment]
There might be other problems.  I've noticed that the invocation of "codesign" is not terribly reliable and py2app already does multiple attempts at signing files in the bundle.

If this is something that's easily reproducible for you:
- Please add multiple "-v" options to the invocation of codesign in py2app/util.py, e.g.:

```
def _dosign(*path):
    subprocess.check_call(
        (
        "codesign",
            "-s",
        "-",
        "--preserve-metadata=identifier,entitlements,flags,runtime",
        "-f",
        "-v", "-v", "-v", #   This line is new
        ) + path
```

I'm hoping this will print which file is seen as problematic. Annoyingly all files should already have been signed by the time the problematic invocation on the entire bundle is done.

And finally: Does the problem go away when you add "import time; time.sleep(1.0)" before the last call to _dosign in codesign_adhoc() (in py2app/util.py)? 

It this something you can reproduce using code that you can share, or with the hello example in py2app repository?

**Comment by ronaldoussoren** [comment]
I can, intermittently, reproduce the issue by running the py2app test suite on a machine running BigSur (x86_64) using the universal2 python installer. 

Adding a retry loop as mentioned in my previous message does not help.
