### ISSUE TITLE
How to includes CoreBluetooth.framework

### ISSUE THREAD

**Issue by YellowDragonLive** [ronaldoussoren/py2app#355]
I try to use Mac OS bluetooth ,
but cannot run.
can anyone help me ?
thanx

```
Traceback (most recent call last):
  File "bleak/__init__.pyc", line 54, in <module>
  File "CoreBluetooth/__init__.pyc", line 10, in <module>
  File "Foundation/__init__.pyc", line 9, in <module>
  File "CoreFoundation/__init__.pyc", line 9, in <module>
  File "objc/__init__.pyc", line 29, in <module>
  File "objc/_bridgesupport.pyc", line 13, in <module>
  File "pkg_resources/__init__.pyc", line 86, in <module>
ModuleNotFoundError: No module named 'pkg_resources.py2_warn'

The above exception was the direct cause of the following exception:

Traceback (most recent call last):
  File "/Users/huanglongsheng/Desktop/work/bleak_web/dist/test_bleak.app/Contents/Resources/__boot__.py", line 411, in <module>
    _run()
  File "/Users/huanglongsheng/Desktop/work/bleak_web/dist/test_bleak.app/Contents/Resources/__boot__.py", line 394, in _run
    exec(compile(source, path, "exec"), globals(), globals())
  File "/Users/huanglongsheng/Desktop/work/bleak_web/dist/test_bleak.app/Contents/Resources/test_bleak.py", line 2, in <module>
    from bleak import BleakScanner
  File "<frozen importlib._bootstrap>", line 983, in _find_and_load
  File "<frozen importlib._bootstrap>", line 967, in _find_and_load_unlocked
  File "<frozen importlib._bootstrap>", line 668, in _load_unlocked
  File "<frozen importlib._bootstrap>", line 638, in _load_backward_compatible
  File "bleak/__init__.pyc", line 56, in <module>
bleak.exc.BleakError: Bleak requires the CoreBluetooth Framework
2021-05-24 15:29:29.022 test_bleak[3090:144861] test_bleak Error
```

```
"""
This is a setup.py script generated by py2applet

Usage:
    python setup.py py2app
"""

from setuptools import setup

APP = ['test_bleak.py']
DATA_FILES = []
OPTIONS = {
    'argv_emulation': True,
    'includes': ["asyncio", "bleak" ],
    'frameworks':["/Library/Developer/CommandLineTools/SDKs/MacOSX11.1.sdk/System/Library/Frameworks/CoreBluetooth.framework"]
}

setup(
    app=APP,
    data_files=DATA_FILES,
    options={'py2app': OPTIONS},
    setup_requires=['py2app'],
)
```

**Comment by ronaldoussoren** [comment]
In general py2app is supposed to detect required libaries automatically, but it obviously doesn't here.

The problem however is not that the CoreBluetooth library wasn't included, but that there's an incompatibility with the included copy of pkg_resources.  What version of setuptools and pyobjc are installed?

BTW. the "frameworks" option is not needed, and might even cause problems here. Py2app should be smart enough to just ignore inclusion of system frameworks, but you're pointing at the SDK files for the framework and py2app doesn't know about those and those stub frameworks are incomplete.

**Comment by YellowDragonLive** [comment]
Thank for your answer.

setuptools : '46.0.0'
objc : '7.1'

**Comment by ronaldoussoren** [comment]
The version of setuptools is pretty old. Could you try updating it?

**Comment by YellowDragonLive** [comment]
It is work .
Thank a lot .
非常感谢(in Chinese)
