### ISSUE TITLE
py2app 0.26 error

### ISSUE THREAD

**Issue by hasii2011** [ronaldoussoren/py2app#378]
On python 3.9.0 with mypy 0.910 installed I can successfully build my app [gittodoist](https://github.com/hasii2011/gittodoistclone)

However, when I upgrade to python 3.9.1 with all my dependencies the same including py2app and mypy I get the following error:

`File "/Users/humberto.a.sanchez.ii/PycharmProjects/gittodoistclone/pyenv-venv-3.9.1/lib/python3.9/site-packages/py2app/util.py", line 497, in byte_compile
    raise RuntimeError("Don't know how to handle %r" % mod.filename)
RuntimeError: Don't know how to handle '/Users/humberto.a.sanchez.ii/PycharmProjects/gittodoistclone/pyenv-venv-3.9.1/lib/python3.9/site-packages/mypy/__init__'`

If I uninstall mypy on the 3.9.1 environment, I can successfully build again.

I use pyenv to switch python versions;   And use venv to create virtual build environments for the above;

As a workaround, I uninstall mypy on 3.9.1

**Comment by MAKOMO** [comment]
Hm. I encounter similar troubles. With mypy installed I cannot build my app with py2app. I have to uninstall it.

**Comment by ronaldoussoren** [comment]
I'm working on this, and expect that this has to do with having both python files and C extensions of the same base name.  If that's the issue the workaround is to install the platform independent wheel for Mypy (although that will be slower).

**Comment by hasii2011** [comment]
Ok, upgrade to 0.26.1 and problem goes away.  Reverted back to 0.26 and problem does not exist anymore;  Not sure what happened;   But I am going to stay on 0.26.1

I am ok with closing this assuming @MAKOMO is ok also

**Comment by MAKOMO** [comment]
Hm. I checked if the order of pip installs resolves this (pip install mypy before or after py2app). No change for me. However, my error message is slightly different from yours:

```
*** filtering dependencies ***
6221 total
47 filtered
183 orphaned
6174 remaining
*** create binaries ***
*** byte compile python files ***
writing byte-compilation script '/tmp/tmpwq8cwvba.py'
/usr/bin/env PYTHONPATH=/Library/Frameworks/Python.framework/Versions/3.9/lib/python3.9/site-packages:/Library/Frameworks/Python.framework/Versions/3.9/lib/python3.9 /Library/Frameworks/Python.framework/Versions/3.9/bin/python3.9 -OO /tmp/tmpwq8cwvba.py
Traceback (most recent call last):
  File "/tmp/tmpwq8cwvba.py", line 1209, in <module>
    byte_compile(files, optimize=2, force=None,
  File "/Library/Frameworks/Python.framework/Versions/3.9/lib/python3.9/site-packages/py2app/util.py", line 497, in byte_compile
    raise RuntimeError("Don't know how to handle %r" % mod.filename)
RuntimeError: Don't know how to handle '/Library/Frameworks/Python.framework/Versions/3.9/lib/python3.9/site-packages/mypy/__init__'
error: command '/usr/bin/env' failed with exit code 1
```

I wonder what mypy has to do with py2app at all. Very strange.
