### ISSUE TITLE
ImportError: No module named cv2.config-3.9

### ISSUE THREAD

**Issue by lycfr** [ronaldoussoren/py2app#389]
I runpython3 setup.py py2app and the error:
'''
running py2app
creating /Users/cfr/PycharmProjects/modelautotest/build/bdist.macosx-10.15-x86_64/python3.9-standalone/app
creating /Users/cfr/PycharmProjects/modelautotest/build/bdist.macosx-10.15-x86_64/python3.9-standalone/app/collect
creating /Users/cfr/PycharmProjects/modelautotest/build/bdist.macosx-10.15-x86_64/python3.9-standalone/app/temp
creating build/bdist.macosx-10.15-x86_64/python3.9-standalone/app/lib-dynload
creating build/bdist.macosx-10.15-x86_64/python3.9-standalone/app/Frameworks
Traceback (most recent call last):
  File "/Users/cfr/PycharmProjects/modelautotest/setup.py", line 18, in <module>
    setup(
  File "/Users/cfr/.pyenv/versions/3.9.7/Library/Frameworks/Python.framework/Versions/3.9/lib/python3.9/site-packages/setuptools/__init__.py", line 153, in setup
    return distutils.core.setup(**attrs)
  File "/Users/cfr/.pyenv/versions/3.9.7/Library/Frameworks/Python.framework/Versions/3.9/lib/python3.9/distutils/core.py", line 148, in setup
    dist.run_commands()
  File "/Users/cfr/.pyenv/versions/3.9.7/Library/Frameworks/Python.framework/Versions/3.9/lib/python3.9/distutils/dist.py", line 966, in run_commands
    self.run_command(cmd)
  File "/Users/cfr/.pyenv/versions/3.9.7/Library/Frameworks/Python.framework/Versions/3.9/lib/python3.9/distutils/dist.py", line 985, in run_command
    cmd_obj.run()
  File "/Users/cfr/.pyenv/versions/3.9.7/Library/Frameworks/Python.framework/Versions/3.9/lib/python3.9/site-packages/py2app/build_app.py", line 932, in run
    self._run()
  File "/Users/cfr/.pyenv/versions/3.9.7/Library/Frameworks/Python.framework/Versions/3.9/lib/python3.9/site-packages/py2app/build_app.py", line 1162, in _run
    self.run_normal()
  File "/Users/cfr/.pyenv/versions/3.9.7/Library/Frameworks/Python.framework/Versions/3.9/lib/python3.9/site-packages/py2app/build_app.py", line 1255, in run_normal
    mf = self.get_modulefinder()
  File "/Users/cfr/.pyenv/versions/3.9.7/Library/Frameworks/Python.framework/Versions/3.9/lib/python3.9/site-packages/py2app/build_app.py", line 1093, in get_modulefinder
    return find_modules(
  File "/Users/cfr/.pyenv/versions/3.9.7/Library/Frameworks/Python.framework/Versions/3.9/lib/python3.9/site-packages/modulegraph/find_modules.py", line 324, in find_modules
    find_needed_modules(mf, scripts, includes, packages)
  File "/Users/cfr/.pyenv/versions/3.9.7/Library/Frameworks/Python.framework/Versions/3.9/lib/python3.9/site-packages/modulegraph/find_modules.py", line 266, in find_needed_modules
    m = mf.import_hook(package, None, ["*"])
  File "/Users/cfr/.pyenv/versions/3.9.7/Library/Frameworks/Python.framework/Versions/3.9/lib/python3.9/site-packages/modulegraph/modulegraph.py", line 1135, in import_hook
    for s in self._ensure_fromlist(m, fromlist):
  File "/Users/cfr/.pyenv/versions/3.9.7/Library/Frameworks/Python.framework/Versions/3.9/lib/python3.9/site-packages/modulegraph/modulegraph.py", line 1265, in _ensure_fromlist
    raise ImportError("No module named " + fullname)
ImportError: No module named cv2.config-3.9
'''
And my setup.py
'''
"""
This is a setup.py script generated by py2applet

Usage:
    python setup.py py2app
"""

from setuptools import setup

APP = ['RunMainUI.py']
DATA_FILES = []
OPTIONS = {
    'argv_emulation': True,
	'packages': ['cv2'],
}

setup(
    app=APP,
    data_files=DATA_FILES,
    options={'py2app': OPTIONS},
    setup_requires=['py2app'],
)
'''
opencv version
'''
opencv-python ==4.5.4.58
'''

How to fix this?

**Comment by lycfr** [comment]
I can use pyinstaller to package successfully

**Comment by sebstryczek** [comment]
@lycfr For me renaming `config-3.9.py` in cv2 dicrectory to `config-3.py` helped

**Comment by lycfr** [comment]
@sebstryczek Thanks, i trying
