### ISSUE TITLE
IndexError: tuple index out of range

### ISSUE THREAD

**Issue by lx1716** [ronaldoussoren/py2app#395]
Here are my SW environments:
- python 3.8
- macOS 12.0.1

I used the command ' python3 setup.py py2app' and below are Traceback

Traceback (most recent call last):
  File "setup.py", line 14, in <module>
    setup(
  File "/Library/Frameworks/Python.framework/Versions/3.8/lib/python3.8/site-packages/setuptools/__init__.py", line 153, in setup
    return distutils.core.setup(**attrs)
  File "/Library/Frameworks/Python.framework/Versions/3.8/lib/python3.8/distutils/core.py", line 148, in setup
    dist.run_commands()
  File "/Library/Frameworks/Python.framework/Versions/3.8/lib/python3.8/distutils/dist.py", line 966, in run_commands
    self.run_command(cmd)
  File "/Library/Frameworks/Python.framework/Versions/3.8/lib/python3.8/distutils/dist.py", line 985, in run_command
    cmd_obj.run()
  File "/Library/Frameworks/Python.framework/Versions/3.8/lib/python3.8/site-packages/py2app/build_app.py", line 932, in run
    self._run()
  File "/Library/Frameworks/Python.framework/Versions/3.8/lib/python3.8/site-packages/py2app/build_app.py", line 1162, in _run
    self.run_normal()
  File "/Library/Frameworks/Python.framework/Versions/3.8/lib/python3.8/site-packages/py2app/build_app.py", line 1396, in run_normal
    o = __import__(m)
  File "shibokensupport/signature/loader.py", line 93, in feature_import
  File "shibokensupport/feature.py", line 127, in feature_import
IndexError: tuple index out of range

**Comment by Mohmmed-Habib** [comment]
same issue below
python 3.8.10
MacOs : 12.1 - M1
PySide6

Traceback (most recent call last):
  File "setup.py", line 19, in <module>
    setup(
  File "/Users/.env/lib/python3.8/site-packages/setuptools/__init__.py", line 153, in setup
    return distutils.core.setup(**attrs)
  File "/Library/Frameworks/Python.framework/Versions/3.8/lib/python3.8/distutils/core.py", line 148, in setup
    dist.run_commands()
  File "/Library/Frameworks/Python.framework/Versions/3.8/lib/python3.8/distutils/dist.py", line 966, in run_commands
    self.run_command(cmd)
  File "/Library/Frameworks/Python.framework/Versions/3.8/lib/python3.8/distutils/dist.py", line 985, in run_command
    cmd_obj.run()
  File "/Documents/env/lib/python3.8/site-packages/py2app/build_app.py", line 932, in run
    self._run()
  File "/Documents/.env/lib/python3.8/site-packages/py2app/build_app.py", line 1162, in _run
    self.run_normal()
  File "Documents/ps4_packge_manager/ps4_pkg_manager/.env/lib/python3.8/site-packages/py2app/build_app.py", line 1396, in run_normal
    o = __import__(m)
  File "shibokensupport/signature/loader.py", line 93, in feature_import
  File "shibokensupport/feature.py", line 127, in feature_import
IndexError: tuple index out of range

**Comment by ronaldoussoren** [comment]
I can reproduce the problem and am working on a fix. Sadly enough fixing this is harder than a trivial adjustment of the existing pyside and. pyside2 recipes.

**Comment by gregvds** [comment]
Python 3.10
MacOS 10.9
Pyside6

Same here:

Traceback (most recent call last):
  File "/Users/gregoirevandenschrick/GIT_repositories/grayscott/setup.py", line 14, in <module>
    setup(
  File "/Users/gregoirevandenschrick/GIT_repositories/grayscott/venv/lib/python3.10/site-packages/setuptools/__init__.py", line 155, in setup
    return distutils.core.setup(**attrs)
  File "/Users/gregoirevandenschrick/GIT_repositories/grayscott/venv/lib/python3.10/site-packages/setuptools/_distutils/core.py", line 148, in setup
    return run_commands(dist)
  File "/Users/gregoirevandenschrick/GIT_repositories/grayscott/venv/lib/python3.10/site-packages/setuptools/_distutils/core.py", line 163, in run_commands
    dist.run_commands()
  File "/Users/gregoirevandenschrick/GIT_repositories/grayscott/venv/lib/python3.10/site-packages/setuptools/_distutils/dist.py", line 967, in run_commands
    self.run_command(cmd)
  File "/Users/gregoirevandenschrick/GIT_repositories/grayscott/venv/lib/python3.10/site-packages/setuptools/_distutils/dist.py", line 986, in run_command
    cmd_obj.run()
  File "/Users/gregoirevandenschrick/GIT_repositories/grayscott/venv/lib/python3.10/site-packages/py2app/build_app.py", line 932, in run
    self._run()
  File "/Users/gregoirevandenschrick/GIT_repositories/grayscott/venv/lib/python3.10/site-packages/py2app/build_app.py", line 1162, in _run
    self.run_normal()
  File "/Users/gregoirevandenschrick/GIT_repositories/grayscott/venv/lib/python3.10/site-packages/py2app/build_app.py", line 1396, in run_normal
    o = __import__(m)
  File "shibokensupport/signature/loader.py", line 93, in feature_import
  File "shibokensupport/feature.py", line 127, in feature_import
IndexError: tuple index out of range

**Comment by VincentCor** [comment]
Python 3.9
MacOS 12.0.1 (M1)
PySide6

Exact same error... I did a lot of tests, tried with different Python versions, etc.

Traceback (most recent call last):
  File "/Users/vincentcormier/Documents/PycharmProjects/OnAirDesktop/setup.py", line 18, in <module>
    setup(
  File "/opt/homebrew/lib/python3.9/site-packages/setuptools/__init__.py", line 155, in setup
    return distutils.core.setup(**attrs)
  File "/opt/homebrew/lib/python3.9/site-packages/setuptools/_distutils/core.py", line 148, in setup
    return run_commands(dist)
  File "/opt/homebrew/lib/python3.9/site-packages/setuptools/_distutils/core.py", line 163, in run_commands
    dist.run_commands()
  File "/opt/homebrew/lib/python3.9/site-packages/setuptools/_distutils/dist.py", line 967, in run_commands
    self.run_command(cmd)
  File "/opt/homebrew/lib/python3.9/site-packages/setuptools/_distutils/dist.py", line 986, in run_command
    cmd_obj.run()
  File "/opt/homebrew/lib/python3.9/site-packages/py2app/build_app.py", line 932, in run
    self._run()
  File "/opt/homebrew/lib/python3.9/site-packages/py2app/build_app.py", line 1162, in _run
    self.run_normal()
  File "/opt/homebrew/lib/python3.9/site-packages/py2app/build_app.py", line 1396, in run_normal
    o = __import__(m)
  File "shibokensupport/signature/loader.py", line 93, in feature_import
  File "shibokensupport/feature.py", line 127, in feature_import
IndexError: tuple index out of range

**Comment by ronaldoussoren** [comment]
Py2app currently is not compatible with PySide6. Pyside2 or PyQt6 should work fine.
