### ISSUE TITLE
ModuleNotFoundError with macOS 64-bit universal2 installer

### ISSUE THREAD

**Issue by YuCao16** [ronaldoussoren/py2app#403]
I'm using python 3.9.8, tkinter 8.6.8 and py2app 0.2.61, and the generated software app has been working without any problems until I tested it on a mac running macOS 10.14.6, which crashed directly to the login screen. This seems to be a bug in macOS and was fixed in a later version. So I would like to use a newer version of tkinter, namely 8.6.12, which is built into the [macOS 64-bit universal2 installer](https://www.python.org/ftp/python/3.9.8/python-3.9.8-macos11.pkg).
But the app generated by the same operation as before does not open properly, it raise Error:
```
Traceback (most recent call last):
  File "/Users/caoyu/Downloads/iamtired.app/Contents/Resources/__boot__.py", line 89, in _recipes_pil_prescript
    import Image
ModuleNotFoundError: No module named 'Image'

During handling of the above exception, another exception occurred:

Traceback (most recent call last):
  File "/Users/caoyu/Downloads/iamtired.app/Contents/Resources/__boot__.py", line 135, in <module>
    _recipes_pil_prescript(['SunImagePlugin', 'ImImagePlugin', 'MspImagePlugin', 'GribStubImagePlugin', 'MpegImagePlugin', 'GbrImagePlugin', 'IcoImagePlugin', 'FtexImagePlugin', 'TiffImagePlugin', 'IptcImagePlugin', 'FpxImagePlugin', 'IcnsImagePlugin', 'JpegImagePlugin', 'BmpImagePlugin', 'PcxImagePlugin', 'PpmImagePlugin', 'DdsImagePlugin', 'BufrStubImagePlugin', 'FliImagePlugin', 'McIdasImagePlugin', 'FitsStubImagePlugin', 'WebPImagePlugin', 'PngImagePlugin', 'MpoImagePlugin', 'Hdf5StubImagePlugin', 'PdfImagePlugin', 'MicImagePlugin', 'GifImagePlugin', 'WmfImagePlugin', 'XpmImagePlugin', 'CurImagePlugin', 'BlpImagePlugin', 'SgiImagePlugin', 'XVThumbImagePlugin', 'PalmImagePlugin', 'PsdImagePlugin', 'Jpeg2KImagePlugin', 'ImtImagePlugin', 'TgaImagePlugin', 'XbmImagePlugin', 'EpsImagePlugin', 'SpiderImagePlugin', 'DcxImagePlugin', 'PcdImagePlugin', 'PixarImagePlugin'])
  File "/Users/caoyu/Downloads/iamtired.app/Contents/Resources/__boot__.py", line 93, in _recipes_pil_prescript
    from PIL import Image
  File "<frozen zipimport>", line 259, in load_module
  File "PIL/Image.pyc", line 89, in <module>
  File "<frozen zipimport>", line 259, in load_module
  File "PIL/_imaging.pyc", line 14, in <module>
  File "PIL/_imaging.pyc", line 10, in __load
  File "imp.pyc", line 342, in load_dynamic
ImportError: dlopen(/Users/caoyu/Downloads/iamtired.app/Contents/Resources/lib/python3.9/lib-dynload/PIL/_imaging.so, 0x0002): tried: '/Users/caoyu/Downloads/iamtired.app/Contents/Resources/lib/python3.9/lib-dynload/PIL/_imaging.so' (mach-o file, but is an incompatible architecture (have 'x86_64', need 'arm64e')), '/usr/local/lib/_imaging.so' (no such file), '/usr/lib/_imaging.so' (no such file)
2022-02-06 22:50:24.483 wont_giveup_thread[84870:3982892] Launch error
2022-02-06 22:50:24.483 wont_giveup_thread[84870:3982892] Launch error
See the py2app website for debugging launch issues

Saving session...completed.
```
If I Switch back to [macOS 64-bit Intel-only installer](https://www.python.org/ftp/python/3.9.8/python-3.9.8-macosx10.9.pkg), It works properly again. What did I do wrong?

**Comment by YuCao16** [comment]
Sorry, one thing I forgot to mention, I have two Macs and I generate the APP on Mac1 and open it on Mac2. The app generated by both Python versions can be opened on Mac1, but the one generated with macOS 64-bit universal2 installer cannot be opened on Mac2.
