### ISSUE TITLE
Error generating setup.py on macOS when a directory name is specified as a resource

### ISSUE THREAD

**Issue by alfwatt** [ronaldoussoren/py2app#453]
Example Code: https://github.com/alfwatt/py2app-directory-resource

```
py2applet --make-setup TestDirectoryResource.py Directory
Traceback (most recent call last):
  File "/Library/Frameworks/Python.framework/Versions/3.10/bin/py2applet", line 8, in <module>
    sys.exit(main())
  File "/Library/Frameworks/Python.framework/Versions/3.10/lib/python3.10/site-packages/py2app/script_py2applet.py", line 125, in main
    path = imp.find_module(os.path.basename(fn))[0]
  File "/Library/Frameworks/Python.framework/Versions/3.10/lib/python3.10/imp.py", line 282, in find_module
    package_directory = os.path.join(entry, name)
  File "/Library/Frameworks/Python.framework/Versions/3.10/lib/python3.10/posixpath.py", line 76, in join
    a = os.fspath(a)
TypeError: expected str, bytes or os.PathLike object, not list
make: *** [setup.py] Error 1
```

**Comment by alfwatt** [comment]
Expected: `Directory` and all it's contents are included in the app bundle on MacOS:

```
TestDirectoryResrouce.app/Contents/Resources/Directory/README.md
```

**Comment by alfwatt** [comment]
Workaround: Include all subpaths in the argument list provided to `py2applet`

**Comment by ronaldoussoren** [comment]
Thanks for the clear report with a reproducer, that made it a lot easier to fix the problem.
