### ISSUE TITLE
from ctypes.macholib import dyld error。couldn't find this module

### ISSUE THREAD

**Issue by hb-2017** [ronaldoussoren/py2app#534]
我在使用 py2app 打包一个 pyqt5 的程序时，我已经完成了打包工作，但是在启动的时候提示异常信息。
﻿
Traceback (most recent call last):
File "/Users/mark/project/dnfm-yolo-tutorial/dist/main.app/Contents/Resources/__boot__.py", line 212, in <module>
_run()
File "/Users/mark/project/dnfm-yolo-tutorial/dist/main.app/Contents/Resources/__boot__.py", line 84, in _run
exec(compile(source, path, "exec"), globals(), globals())
File "/Users/mark/project/dnfm-yolo-tutorial/dist/main.app/Contents/Resources/main.py", line 8, in <module>
from device_manager.scrcpy_adb import ScrcpyADB
File "<frozen zipimport>", line 259, in load_module
File "device_manager/scrcpy_adb.pyc", line 17, in <module>
ImportError: cannot import name 'YOLOv10' from 'ultralytics' (/Users/mark/project/dnfm-yolo-tutorial/dist/main.app/Contents/Resources/lib/python3.8/ultralytics/__init__.py)
﻿
我在查看 __boot__.py 文件时，发现 _setup_ctypes 中的 from ctypes.macholib import dyld 报错，不能正确找到这个模块。
﻿
<img width="750" alt="image" src="https://github.com/user-attachments/assets/30bcf697-61d0-4eb4-846c-3fbb34fde9c4">

﻿
我应该如何解决？

**Comment by hb-2017** [comment]
There is still an issue with this file, and the Distribution in the find_ eggs_in_zip method cannot be found. I added pkd_sources earlier to make it run properly.

<img width="826" alt="image" src="https://github.com/user-attachments/assets/7283d48f-ce50-41e3-af07-1ef4090999ba">

<img width="806" alt="image" src="https://github.com/user-attachments/assets/3b3ba32f-2db6-4c4d-b0ec-a9dcd369c8db">

**Comment by hb-2017** [comment]
I found that the reason why I encountered this problem may be that I manually copied the dependency packages in the virtual environment to the lib directory in the resource directory. I am doing this because I am trying to solve the following problem.

/Users/mark/project/dnfm-yolo-tutorial/dist/main.app/Contents/MacOS/main ;  exit;
mark@Mark  ~ % /Users/mark/project/dnfm-yolo-tutorial/dist/main.app/Contents/MacOS/main ;  exit;
requests/__init__.pyc:86: RequestsDependencyWarning: Unable to find acceptable character detection dependency (chardet or charset_normalizer).
init
Traceback (most recent call last):
File "/Users/mark/project/dnfm-yolo-tutorial/dist/main.app/Contents/Resources/__boot__.py",  line 212, in <module>
_run()
File "/Users/mark/project/dnfm-yolo-tutorial/dist/main.app/Contents/Resources/__boot__.py", line 84, in _run
exec(compile(source, path, "exec"), globals(), globals())
File "/Users/mark/project/dnfm-yolo-tutorial/dist/main.app/Contents/Resources/main.py", line 8, in <module>
from device_manager.scrcpy_adb import ScrcpyADB
File "<frozen importlib._ bootstrap>",  line 991, in _find_and_load
File "<frozen importlib._ bootstrap>",  line 975, in _find_and_load_unlocked
File "<frozen importlib._ bootstrap>",  line 655, in _load_unlocked
File "<frozen importlib._ bootstrap>",  line 618, in _load_backward_compatible
File "<frozen zipimport>",  line 259, in load_module
File "device_manager/scrcpy_adb.pyc",  line 17, in <module>
File "/Users/mark/project/dnfm-yolo-tutorial/dist/main.app/Contents/Resources/lib/python3.8/ultralytics/__init__.py", line 5, in <module>
from ultralytics.data.explorer.explorer import Explorer
File "/Users/mark/project/dnfm-yolo-tutorial/dist/main.app/Contents/Resources/lib/python3.8/ultralytics/data/__init__.py", line 3, in <module>
from .base import BaseDataset
File "/Users/mark/project/dnfm-yolo-tutorial/dist/main.app/Contents/Resources/lib/python3.8/ultralytics/data/base.py",  line 17, in <module>
from ultralytics.utils import DEFAULT_CFG, LOCAL_RANK, LOGGER, NUM_THREADS, TQDM
File "/Users/mark/project/dnfm-yolo-tutorial/dist/main.app/Contents/Resources/lib/python3.8/ultralytics/utils/__init__.py",  line 1025, in <module>
SETTINGS = SettingsManager()  # initialize settings
File "/Users/mark/project/dnfm-yolo-tutorial/dist/main.app/Contents/Resources/lib/python3.8/ultralytics/utils/__init__.py",  line 923, in __init__
from ultralytics.utils.torch_utils import torch_distributed_zero_first
File "/Users/mark/project/dnfm-yolo-tutorial/dist/main.app/Contents/Resources/lib/python3.8/ultralytics/utils/torch_utils.py",  line 17, in <module>
import torchvision
File "/Users/mark/project/dnfm-yolo-tutorial/dist/main.app/Contents/Resources/lib/python3.8/torchvision/__init__.py", line 6, in <module>
from torchvision import _meta_registrations, datasets, io, models, ops, transforms, utils
File "/Users/mark/project/dnfm-yolo-tutorial/dist/main.app/Contents/Resources/lib/python3.8/torchvision/_meta_registrations.py",  line 164, in <module>
def meta_nms(dets,  scores, iou_threshold):
File "/Users/mark/project/dnfm-yolo-tutorial/dist/main.app/Contents/Resources/lib/python3.8/torch/library.py", line 467, in inner
handle = entry.abstract_impl.register(func_to_register, source)
File "/Users/mark/project/dnfm-yolo-tutorial/dist/main.app/Contents/Resources/lib/python3.8/torch/_library/abstract_impl.py",  line 30, in register
if torch._C._dispatch_has_kernel_for_dispatch_key(self.qualname, "Meta"):
RuntimeError: operator torchvision::nms does not exist
2024-09-23 19:53:22.476 main[61855:8357347] Launch error
2024-09-23 19:53:22.476 main[61855:8357347] Launch error
See the py2app website for debugging launch issues

My code can be packaged normally, but I got this error message when I started it.

I can run it normally in my own local code, and there are no compatibility issues between torchvision and torch versions.

After encountering this error, I also tried to launch main.exe directly in the resources directory. I found that it can also be launched, but if I directly launch the. app, it will crash.

<img width="381" alt="image" src="https://github.com/user-attachments/assets/669c38dd-29c2-496a-ab1c-b15705d49c13">


My project is to display the phone screen through a GUI interface and detect the screen through YOLOV10.

May I ask how I should solve this problem?
