### ISSUE TITLE
py2app issues with PyQt4

### ISSUE THREAD

**Issue by ronaldoussoren** [ronaldoussoren/py2app#89]
**[Original report](https://bitbucket.org/ronaldoussoren/py2app/issue/89) by Thomas Crawford (Bitbucket: [tomcraw](https://bitbucket.org/tomcraw), GitHub: [tomcraw](https://github.com/tomcraw)).**

----------------------------------------

Hi,

I am at a loss as to how to proceed.  I have tried every combination of setup.py file I can find on the web.  I have found all the information about making empty "qt.conf" files and the whatnot, but I am stuck.

If I start my application from the terminal:
Zymurgy.app/Contents/MacOS/Zymurgy

I get the following error:
Traceback (most recent call last):
  File "/Users/tommyc/Documents/Zymurgy/Zymurgy_trunk/dist/Zymurgy.app/Contents/Resources/__boot__.py", line 43, in <module>
    _run()
  File "/Users/tommyc/Documents/Zymurgy/Zymurgy_trunk/dist/Zymurgy.app/Contents/Resources/__boot__.py", line 38, in _run
    exec(compile(source, path, 'exec'), globals(), globals())
  File "/Users/tommyc/Documents/Zymurgy/Zymurgy_trunk/dist/Zymurgy.app/Contents/Resources/zymurgy.py", line 20, in <module>
    from PyQt4.QtGui import *
ImportError: No module named QtGui

I have tried the following for setup.py files:

```
#!from setuptools import setup

APP = ['zymurgy.py']
OPTIONS = {'argv_emulation': False}

setup(
    app=APP,
    options={'py2app': OPTIONS},
    setup_requires=['py2app'],
python


```

or 

```
from setuptools import setup

APP = ['zymurgy.py']

OPTIONS = {'includes': ['sip', 'PyQt4', 'PyQt4.QtCore', 'PyQt4.QtGui', 'matplotlib', 'numpy', 'scipy', 'pandas', 'sqlite3'],  #],
           'argv_emulation': False}


setup(
        name = "Zymurgy",
        version="1.0.0 beta",  
        app=APP,
        options={'py2app': OPTIONS},
        setup_requires=['py2app'],
)


```

I am using Python 3.2.3 installed via Homebrew
PyQt4 is installed and compiled from source

thanks for any help you could give,

Tommy

**Comment by ronaldoussoren** [comment]
Closing this, PyQt4 is too old by now.
